# Generated by Django 4.0.6 on 2022-07-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
